Deb packaging

diff --git a/.github/workflows/Linux-pack.yml b/.github/workflows/Linux-pack.yml
--- a/.github/workflows/Linux-pack.yml
+++ b/.github/workflows/Linux-pack.yml
@@ -29,99 +29,99 @@ env:
   PACKPACK_REPO: flameshot-org/packpack
 
 jobs:
-#   deb-pack:
-#     name: Build deb on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
-#     runs-on: ubuntu-latest
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         dist:
-#           - {
-#               name: debian-11,
-#               os: debian,
-#               symbol: bullseye,
-#               arch: amd64
-#             }
-#           - {
-#               name: debian-12,
-#               os: debian,
-#               symbol: bookworm,
-#               arch: amd64
-#             }
-#           - {
-#               name: ubuntu-22.04,
-#               os: ubuntu,
-#               symbol: jammy,
-#               arch: amd64
-#             }
-#           - {
-#               name: ubuntu-24.04,
-#               os: ubuntu,
-#               symbol: noble,
-#               arch: amd64
-#             }
-#
-#     steps:
-#       - name: Set up Docker Buildx
-#         uses: docker/setup-buildx-action@v3
-#       - name: Set up QEMU
-#         uses: docker/setup-qemu-action@v3
-#       - name: Checkout Source code
-#         if: github.event_name == 'push'
-#         uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0
-#           ref: master
-#       - name: Checkout Source code
-#         if: github.event_name == 'pull_request'
-#         uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0
-#           ref: ${{ github.event.pull_request.head.sha }}
-#       - name: Set env & Print flameshot version
-#         shell: bash
-#         run: |
-#           last_committed_tag=$(git tag -l --sort=-v:refname | head -1)
-#           git_revno=$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
-#           git_hash=$(git rev-parse --short HEAD)
-#           ver_info=${last_committed_tag}+git${git_revno}.${git_hash}
-#           echo "=======FLAMESHOT VERSION========"
-#           echo ${last_committed_tag:1}
-#           echo "Details: ${ver_info}"
-#           echo "================================"
-#           echo "VERSION=${last_committed_tag:1}" >> $GITHUB_ENV
-#           echo "VER_INFO=${ver_info}" >> $GITHUB_ENV
-#       - name: Get packpack tool
-#         uses: actions/checkout@v4
-#         with:
-#           repository: ${{ env.PACKPACK_REPO }}
-#           path: tools
-#           ref: multiarch
-#           set-safe-directory: $GITHUB_WORKSPACE/tools
-#       - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
-#         env:
-#           OS: ${{ matrix.dist.os }}
-#           DIST: ${{ matrix.dist.symbol }}
-#           #DOCKER_ARCH: ${{ matrix.dist.arch }}
-#           ## I cannot see if ARCH is used anywhere. Should we remove it?
-#           #ARCH: ${{ matrix.dist.arch }}
-#         run: |
-#           cp -r $GITHUB_WORKSPACE/packaging/debian $GITHUB_WORKSPACE
-#           bash $GITHUB_WORKSPACE/tools/packpack
-#           mv $GITHUB_WORKSPACE/build/${PRODUCT}_${VERSION}-${RELEASE}_${{ matrix.dist.arch }}.deb $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb
-#       - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
-#         run: |
-#           cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
-#           sha256sum ${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb | tee ${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb.sha256sum
-#       - name: Artifact Upload
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
-#           path: |
-#             ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-${{ env.RELEASE }}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb
-#             ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-${{ env.RELEASE }}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb.sha256sum
-#           overwrite: true
-#
+  deb-pack:
+    name: Build deb on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        dist:
+#          - {
+#              name: debian-11,
+#              os: debian,
+#              symbol: bullseye,
+#              arch: amd64
+#            }
+          - {
+              name: debian-12,
+              os: debian,
+              symbol: bookworm,
+              arch: amd64
+            }
+          - {
+              name: ubuntu-22.04,
+              os: ubuntu,
+              symbol: jammy,
+              arch: amd64
+            }
+          - {
+              name: ubuntu-24.04,
+              os: ubuntu,
+              symbol: noble,
+              arch: amd64
+            }
+
+    steps:
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Checkout Source code
+        if: github.event_name == 'push'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: master
+      - name: Checkout Source code
+        if: github.event_name == 'pull_request'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Set env & Print flameshot version
+        shell: bash
+        run: |
+          last_committed_tag=$(git tag -l --sort=-v:refname | head -1)
+          git_revno=$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
+          git_hash=$(git rev-parse --short HEAD)
+          ver_info=${last_committed_tag}+git${git_revno}.${git_hash}
+          echo "=======FLAMESHOT VERSION========"
+          echo ${last_committed_tag:1}
+          echo "Details: ${ver_info}"
+          echo "================================"
+          echo "VERSION=${last_committed_tag:1}" >> $GITHUB_ENV
+          echo "VER_INFO=${ver_info}" >> $GITHUB_ENV
+      - name: Get packpack tool
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ env.PACKPACK_REPO }}
+          path: tools
+          ref: multiarch
+          set-safe-directory: $GITHUB_WORKSPACE/tools
+      - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
+        env:
+          OS: ${{ matrix.dist.os }}
+          DIST: ${{ matrix.dist.symbol }}
+          #DOCKER_ARCH: ${{ matrix.dist.arch }}
+          ## I cannot see if ARCH is used anywhere. Should we remove it?
+          #ARCH: ${{ matrix.dist.arch }}
+        run: |
+          cp -r $GITHUB_WORKSPACE/packaging/debian $GITHUB_WORKSPACE
+          bash $GITHUB_WORKSPACE/tools/packpack
+          mv $GITHUB_WORKSPACE/build/${PRODUCT}_${VERSION}-${RELEASE}_${{ matrix.dist.arch }}.deb $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb
+      - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
+        run: |
+          cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
+          sha256sum ${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb | tee ${PRODUCT}-${VERSION}-${RELEASE}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb.sha256sum
+      - name: Artifact Upload
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
+          path: |
+            ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-${{ env.RELEASE }}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb
+            ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-${{ env.RELEASE }}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb.sha256sum
+          overwrite: true
+
 #   rpm-pack:
 #     name: Build rpm on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
 #     runs-on: ubuntu-latest
@@ -403,7 +403,7 @@ jobs:
       - name: Setup Flathub
         run: |
           flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
-          flatpak install -y --noninteractive flathub org.kde.Sdk//5.15 org.kde.Platform//5.15
+          flatpak install -y --noninteractive flathub org.kde.Sdk//6.9 org.kde.Platform//6.9
       - name: Packaging flatpak
         run: |
           BUNDLE="org.flameshot.Flameshot_${VERSION}_x86_64.flatpak"
