RPM

diff --git a/.github/workflows/Linux-pack.yml b/.github/workflows/Linux-pack.yml
--- a/.github/workflows/Linux-pack.yml
+++ b/.github/workflows/Linux-pack.yml
@@ -138,119 +138,130 @@ jobs:
             ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-${{ env.RELEASE }}.${{ matrix.dist.name }}.${{ matrix.dist.arch }}.deb.sha256sum
           overwrite: true
 
-#   rpm-pack:
-#     name: Build rpm on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
-#     runs-on: ubuntu-latest
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         dist:
-#           - {
-#               name: fedora-41,
-#               os: fedora,
-#               symbol: 41,
-#               arch: x86_64
-#             }
-#           - {
-#               name: fedora-42,
-#               os: fedora,
-#               symbol: 42,
-#               arch: x86_64
-#             }
-#           - {
-#               name: opensuse-leap-15.6,
-#               os: opensuse-leap,
-#               symbol: 15.6,
-#               arch: x86_64
-#             }
-#     steps:
-#       - name: Checkout Source code
-#         if: github.event_name == 'push'
-#         uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0
-#           ref: master
-#       - name: Checkout Source code
-#         if: github.event_name == 'pull_request'
-#         uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0
-#           ref: ${{ github.event.pull_request.head.sha }}
-#       - name: Set env & Print flameshot version
-#         shell: bash
-#         run: |
-#           last_committed_tag=$(git tag -l --sort=-v:refname | head -1)
-#           git_revno=$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
-#           git_hash=$(git rev-parse --short HEAD)
-#           ver_info=${last_committed_tag}+git${git_revno}.${git_hash}
-#           echo "=======FLAMESHOT VERSION========"
-#           echo ${last_committed_tag:1}
-#           echo "Details: ${ver_info}"
-#           echo "================================"
-#           echo "VERSION=${last_committed_tag:1}" >> $GITHUB_ENV
-#           echo "VER_INFO=${ver_info}" >> $GITHUB_ENV
-#       - name: Get packpack tool
-#         uses: actions/checkout@v4
-#         with:
-#           repository: ${{ env.PACKPACK_REPO }}
-#           path: tools
-#           ref: master
-#           set-safe-directory: $GITHUB_WORKSPACE/tools
-#       - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
-#         if: matrix.dist.os == 'fedora'
-#         run: |
-#           mkdir $GITHUB_WORKSPACE/rpm
-#           cp $GITHUB_WORKSPACE/packaging/rpm/fedora/flameshot.spec $GITHUB_WORKSPACE/rpm
-#           bash $GITHUB_WORKSPACE/tools/packpack
-#         env:
-#           OS: ${{ matrix.dist.os }}
-#           DIST: ${{ matrix.dist.symbol }}
-#       - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
-#         if: matrix.dist.os == 'opensuse-leap'
-#         run: |
-#           mkdir $GITHUB_WORKSPACE/rpm
-#           cp $GITHUB_WORKSPACE/packaging/rpm/opensuse/flameshot.spec $GITHUB_WORKSPACE/rpm
-#           bash $GITHUB_WORKSPACE/tools/packpack
-#         env:
-#           OS: ${{ matrix.dist.os }}
-#           DIST: ${{ matrix.dist.symbol }}
-#       - name: Package Clean
-#         if: matrix.dist.os == 'fedora'
-#         run: |
-#           rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-debuginfo-*.rpm
-#           rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-debugsource-*.rpm
-#           rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-*.src.rpm
-#           rm -f ${{ github.workspace }}/build/build.log
-#       - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
-#         if: matrix.dist.os == 'fedora'
-#         run: |
-#           cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
-#           sha256sum ${PRODUCT}-${VERSION}-${RELEASE}.fc*.${{ matrix.dist.arch }}.rpm | tee ${PRODUCT}-${VERSION}-${RELEASE}.fc${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
-#       - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
-#         if: matrix.dist.os == 'opensuse-leap'
-#         run: |
-#           mv $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-lp*.${{ matrix.dist.arch }}.rpm $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm
-#           cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
-#           sha256sum ${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm | tee ${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
-#       - name: Artifact Upload
-#         if: matrix.dist.os == 'fedora'
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
-#           path: |
-#             ${{ github.workspace }}/build/
-#           overwrite: true
-#
-#       - name: Artifact Upload
-#         if: matrix.dist.os == 'opensuse-leap'
-#         uses: actions/upload-artifact@v4
-#         with:
-#           name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
-#           path: |
-#             ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm
-#             ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
-#           overwrite: true
-#
+  rpm-pack:
+    name: Build rpm on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        dist:
+          - {
+              name: fedora-41,
+              os: fedora,
+              symbol: 41,
+              arch: x86_64
+            }
+          - {
+              name: fedora-42,
+              os: fedora,
+              symbol: 42,
+              arch: x86_64
+            }
+    steps:
+      - name: Checkout Source code
+        if: github.event_name == 'push'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+#          ref: master
+
+      - name: Checkout Source code
+        if: github.event_name == 'pull_request'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      - name: Checkout Source code
+        if: github.event_name == 'workflow_dispatch'
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Set env & Print flameshot version
+        shell: bash
+        run: |
+          last_committed_tag=$(git tag -l --sort=-v:refname | head -1)
+          git_revno=$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
+          git_hash=$(git rev-parse --short HEAD)
+          ver_info=${last_committed_tag}+git${git_revno}.${git_hash}
+          echo "=======FLAMESHOT VERSION========"
+          echo ${last_committed_tag:1}
+          echo "Details: ${ver_info}"
+          echo "================================"
+          # This will allow to build pre-preleases without git tag
+          # echo "VERSION=${last_committed_tag:1}" >> $GITHUB_ENV
+          echo "VERSION=$(cat CMakeLists.txt |grep 'set.*(.*FLAMESHOT_VERSION' | sed 's/[^0-9.]*//' |sed 's/)//g')" >> $GITHUB_ENV
+          echo "VER_INFO=${ver_info}" >> $GITHUB_ENV
+
+      - name: Get packpack tool
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ env.PACKPACK_REPO }}
+          path: tools
+          ref: master
+          set-safe-directory: $GITHUB_WORKSPACE/tools
+
+      - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
+        if: matrix.dist.os == 'fedora'
+        run: |
+          mkdir $GITHUB_WORKSPACE/rpm
+          cp $GITHUB_WORKSPACE/packaging/rpm/fedora/flameshot.spec $GITHUB_WORKSPACE/rpm
+          bash $GITHUB_WORKSPACE/tools/packpack
+        env:
+          OS: ${{ matrix.dist.os }}
+          DIST: ${{ matrix.dist.symbol }}
+
+      - name: Packaging on ${{ matrix.dist.name }} ${{ matrix.dist.arch }}
+        if: matrix.dist.os == 'opensuse-leap'
+        run: |
+          mkdir $GITHUB_WORKSPACE/rpm
+          cp $GITHUB_WORKSPACE/packaging/rpm/opensuse/flameshot.spec $GITHUB_WORKSPACE/rpm
+          bash $GITHUB_WORKSPACE/tools/packpack
+        env:
+          OS: ${{ matrix.dist.os }}
+          DIST: ${{ matrix.dist.symbol }}
+
+      - name: Package Clean
+        if: matrix.dist.os == 'fedora'
+        run: |
+          rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-debuginfo-*.rpm
+          rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-debugsource-*.rpm
+          rm -f ${{ github.workspace }}/build/${{ env.PRODUCT }}-*.src.rpm
+          rm -f ${{ github.workspace }}/build/build.log
+
+      - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
+        if: matrix.dist.os == 'fedora'
+        run: |
+          cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
+          sha256sum ${PRODUCT}-${VERSION}-${RELEASE}.fc*.${{ matrix.dist.arch }}.rpm | tee ${PRODUCT}-${VERSION}-${RELEASE}.fc${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
+
+      - name: SHA256Sum of ${{ matrix.dist.name }} ${{ matrix.dist.arch }} package
+        if: matrix.dist.os == 'opensuse-leap'
+        run: |
+          mv $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-lp*.${{ matrix.dist.arch }}.rpm $GITHUB_WORKSPACE/build/${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm
+          cd "$GITHUB_WORKSPACE/build/" || { >&2 echo "Cannot cd to '$GITHUB_WORKSPACE/build/'!"; exit 11 ; }
+          sha256sum ${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm | tee ${PRODUCT}-${VERSION}-${RELEASE}-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
+
+      - name: Artifact Upload
+        if: matrix.dist.os == 'fedora'
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
+          path: |
+            ${{ github.workspace }}/build/
+          overwrite: true
+
+      - name: Artifact Upload
+        if: matrix.dist.os == 'opensuse-leap'
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.PRODUCT }}-${{ env.VER_INFO }}-artifact-${{ matrix.dist.name }}-${{ matrix.dist.arch }}
+          path: |
+            ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm
+            ${{ github.workspace }}/build/${{ env.PRODUCT }}-*-lp${{ matrix.dist.symbol }}.${{ matrix.dist.arch }}.rpm.sha256sum
+          overwrite: true
+
 #   appimage-pack:
 #     name: Build appimage on ${{ matrix.config.name }}
 #     runs-on: ubuntu-latest
